## Live coding: Module 2

In [3]:
import pandas as pd
import numpy as np

In [4]:
gallup = pd.read_csv('USAIPO1936-0053.csv')

In [10]:
gallup.head(3).T

,0,1,2
form,NaN,NaN,NaN
state,Indiana,Illinois,Michigan
region,East Central,East Central,East Central
female,Male,Male,Male
age,NaN,NaN,NaN
class,Av+,Av+,Av
OCCUPATION1,Skilled workers,Skilled workers,Business
OCCUPATION2,NaN,NaN,NaN
OCCUPATION3,NaN,NaN,NaN
black,NaN,NaN,NaN
size,Urban,Urban,Urban
education,NaN,NaN,NaN
AGE_3WAY,NaN,NaN,NaN
AGE40,NaN,NaN,NaN
OCC8,Labor,Labor,Professional
prof,Not Professional,Not Professional,Professional
REGION4,Midwest,Midwest,Midwest
EDU_RECODE,NaN,NaN,NaN
VOTE_PRO,Landon,Landon,Landon
VOTE_RETRO,Hoover,Hoover,Hoover
PHONE_RECODE,NaN,NaN,NaN
CAR_RECODE,NaN,NaN,NaN
ballot,53,53,53
Q1,Yes,Yes,No
Q2,Yes,NaN,No
Q3,Yes,Yes,Yes
Q4A,Roosevelt,Landon,Landon
Q4B,Roosevelt,Landon,Landon
Q4C,Landon,Landon,Landon
Q5A,Landon,Landon,Landon
Q5B,"Yes, voted for Hoover","Yes, voted for Hoover","Yes, voted for Hoover"
farm,Non-Farm,Non-Farm,Non-Farm
SIZE3,Urban,Urban,Urban
urban,Urban,Urban,Urban
StPOAbrv,in,il,mi
SOUTH11,Non-South,Non-South,Non-South
SOUTH11xBLACK,NaN,NaN,NaN
SOUTH12,Non-South,Non-South,Non-South
SOUTH12xBLACK,NaN,NaN,NaN
south,Non-South,Non-South,Non-South
SOUTHxBLACK,NaN,NaN,NaN
year,1936,1936,1936
WtPubFeas,NaN,NaN,NaN
WtVotFeas,NaN,NaN,NaN

In [12]:
pd.crosstab(gallup['Q5A'], gallup['Q3'])
# Q5A is on the columns, Q3 is on the rows

Q3            No   Yes
Q5A
Landon       921   820
Lemke         41   109
Other party    6     6
Roosevelt    442  2048
Thomas        10    41

In [13]:
college = pd.read_stata('31123182.dta')

In [16]:
pd.set_option('display.max_rows', 91)
college.head(3).T

,0,1,2
RecordNo,10011,10013,10015
rightdir,Do not know,Right direction,Wrong track
MIP_PA,"Government, politicians",Donald Trump,"Government, politicians"
fintoday,About the same,Worse off,Worse off
finfut,Worse off,Worse off,Worse off
AI1,Every day,Once in a while,Most days
AI2,Somewhat nervous,Somewhat nervous,Somewhat nervous
AI3,Very concerned,Not currently employed,Not currently employed
AI4,"Yes, probably","Yes,definitely","Yes,definitely"
AI5,"No, probably not",Do not know,"No, probably not"
D1_25,Very dissatisfied,Somewhat dissatisfied,Very dissatisfied
D1,Strongly agree,Somewhat agree,Strongly agree
D2,Strongly disagree,Strongly disagree,Strongly disagree
D3,Strongly agree,Somewhat agree,Strongly agree
D5,Strongly agree,Strongly agree,Strongly agree
D6,Strongly agree,Strongly agree,Strongly agree
SEL_D7,d7cert,d7con,d7con
D7_CON,NaN,Congress has given up too much power to the p...,Congress has given up too much power to the p...
D7_CRT,The courts have given up too much power to the...,NaN,NaN
D8,Overstepped limits of presidency,Overstepped limits of presidency,Overstepped limits of presidency
rategov,Excellent,Good,Excellent
ratepres,A poor job,A poor job,A poor job
RATETRUMP_A,F=Failing,D=Below average,F=Failing
RATETRUMP_B,F=Failing,D=Below average,F=Failing
RATETRUMP_C,F=Failing,F=Failing,F=Failing
RATETRUMP_D,F=Failing,F=Failing,F=Failing
RATETRUMP_E,D=Below average,C=Average,F=Failing
OBB1,Strongly oppose,Somewhat oppose,Strongly oppose
OBB2,Much worse,Somewhat worse,Much worse
OBB3,Greatly decrease,Somewhat decrease,Greatly decrease
OBB4,Worse off,About the same,Worse off
N1,Very closely,Very closely,Very closely
N2,Very closely,Somewhat closely,Very closely
reg,Yes,Yes,Yes
regparty,Democrat,Independent,Democrat
ptch,No,No,No
ptsat,Somewhat dissatisfied,NaN,Somewhat dissatisfied
VOTE_NOV,Certain to vote,Certain to vote,Certain to vote
POL_INT,Very interested,Very interested,Very interested
SSC_CD,NaN,NaN,Do not know
SSC_KD,NaN,NaN,NaN
SSC_DW,Yes,Yes,NaN
genbalh,Democratic Party's candidate,Democratic Party's candidate,Democratic Party's candidate
VOT24,Yes,Yes,Yes
VOT24PREF,Kamala Harris,Kamala Harris,Kamala Harris
age,60,71,Prefer not to answer
educ,Bachelor's degree,Some college,"Postgraduate degree (Master's degree, Doctorat..."
mar,Married,Divorced,Married
primnews,"Network television, such as ABC, CBS, or NBC",The Internet (other than social media),Daily newspaper (such as the Inquirer or Post...
cabnet,NaN,NaN,NaN
gpint,Most of the time,Most of the time,Most of the time
ideo,moderate,moderate,extremely liberal
IDEO1,Moderate,Moderate,Liberal
PRTY1,Independent,Independent,Democrat
party,lean democrat,lean democrat,strong democrat
gun,Yes,No,No
GUN2,Somewhat favor,Strongly favor,Strongly favor
RACEM1,White,White,White
RACEM2,NaN,NaN,NaN
RACEM3,NaN,NaN,NaN
rel,Catholic,Not affiliated with any religion,Some other religion
bac,No,No,No
abort,Legal under any circumstances,Legal under certain circumstances,Legal under any circumstances
work,Full-time,Retired,Retired
income,Prefer not to answer,"$35,000-50,000",Prefer not to answer
done,Female,Male,Male
INT99,Completed Online,Completed Online,Completed Online
oparty,Dem,Ind,Dem
ogender,F,M,M
US_CD,6,6,6
oage,59,71,72
cntycat,Southeast,Southeast,Southeast
agerange,55-64,65 and over,NaN
reage,Over 55,Over 55,NaN
reEDUC,College degree,Some college,College degree
reREL,Catholic,"Other, unaffiliated","Other, unaffiliated"
reWORK,Fulltime,Retired,Retired
reINC,NaN,35-75,NaN
reMAR,Married,Not currently married,Married
rural,Urban,Urban,Urban
CNTYCAT5,Philadelphia & SE,Philadelphia & SE,Philadelphia & SE
reIDEO,Moderate,Moderate,Liberal
collegegrad,College Degree,No College Degree,College Degree
nchsur,Large Fringe Metro,Large Fringe Metro,Large Fringe Metro
RegYear,1996.0,1996.0,1991.0
RACE4,White,White,White
VOTE24WT,Harris,Harris,Harris
sagerange,55-64,65 and over,65 and over
s_reage,Over 55,Over 55,Over 55
likely,Likely voter,Likely voter,Likely voter
wt,0.311062,0.883655,0.135879

In [19]:
widths = [4,
 3,
 1,
 1,
 1,
 3,
 2,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 1,
 1,
 3,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 3,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 1,
 3,
 3,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 2,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 2,
 2,
 2,
 1,
 2,
 1,
 2,
 1,
 2,
 2,
 1,
 1,
 1,
 1]

In [22]:
usia = pd.read_fwf('i20068.dat', widths=widths, header=None)

In [23]:
usia

,0,1,2,3,4,5,6,7,8,9,...,126,127,128,129,130,131,132,133,134,135
0,1,155.0,2.0,1.0,2.0,108.0,12.0,14.0,2.0,3.0,...,1.0,5.0,6.0,2.0,4.0,4.0,NaN,NaN,6.0,4.0
1,2,155.0,2.0,1.0,2.0,120.0,9.0,13.0,1.0,1.0,...,1.0,6.0,6.0,1.0,NaN,NaN,NaN,NaN,NaN,3.0
2,3,155.0,2.0,1.0,2.0,102.0,14.0,NaN,2.0,2.0,...,1.0,5.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,5.0
3,4,155.0,2.0,1.0,2.0,129.0,9.0,13.0,2.0,3.0,...,1.0,6.0,5.0,1.0,NaN,NaN,NaN,NaN,NaN,3.0
4,5,155.0,2.0,1.0,1.0,1.0,13.0,9.0,2.0,2.0,...,1.0,6.0,7.0,1.0,NaN,NaN,NaN,NaN,NaN,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2033,2248,283.0,2.0,2.0,2.0,102.0,6.0,11.0,2.0,2.0,...,1.0,2.0,17.0,2.0,5.0,7.0,NaN,NaN,7.0,2.0
2034,2249,283.0,2.0,2.0,8.0,NaN,98.0,NaN,8.0,8.0,...,1.0,5.0,17.0,2.0,4.0,1.0,NaN,NaN,1.0,7.0
2035,2250,283.0,2.0,2.0,9.0,NaN,98.0,NaN,3.0,3.0,...,1.0,3.0,17.0,2.0,3.0,6.0,NaN,NaN,4.0,4.0
2036,2251,255.0,1.0,2.0,2.0,163.0,9.0,6.0,3.0,4.0,...,1.0,1.0,17.0,2.0,3.0,6.0,NaN,NaN,1.0,5.0
2037,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN